version: '3'
services:
  hugo:
    image: hugomods/hugo:exts-non-root
    container_name: hugo-dev
    volumes:
      - ./:/src
      - ~/hugo_cache:/tmp/hugo_cache
    ports:
      - "1313:1313"
    command: server -D --bind 0.0.0.0

