name: Node API CI/CD

on:
  push:
    branches: [ "prod" "infra-milestone-ec2" ]
    paths:
      - "hello-docker-node/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node dependencies
        working-directory: hello-docker-node
        run: npm install

      - name: Test (ignore failures)
        working-directory: hello-docker-node
        run: npm test || echo "no tests"

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=node-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Build & Push
        run: |
          REPO=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NODE }}
          docker build -t $REPO:$IMAGE_TAG hello-docker-node
          docker tag $REPO:$IMAGE_TAG $REPO:latest
          docker push $REPO:$IMAGE_TAG
          docker push $REPO:latest

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve \
              -var="image_tag=$IMAGE_TAG" \
              -var="aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" \
              -var="ecr_repo_node=${{ secrets.ECR_REPO_NODE }}" \
              -var="aws_region=${{ secrets.AWS_REGION }}" \
              -var="key_name=${{ secrets.EC2_KEY_NAME }}"
