name: Hugo CI/CD

on:
  push:
    branches: [ "main", "prod" ]
    paths:
      - "hugo/**"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=hugo-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & push Hugo image
        run: |
          REPO=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_HUGO }}
          docker build -t $REPO:$IMAGE_TAG ./hugo
          docker tag $REPO:$IMAGE_TAG $REPO:latest
          docker push $REPO:$IMAGE_TAG
          docker push $REPO:latest
