name: Build OPS AMI

on:
  push:
    paths:
      - infra/packer/ops/**
  workflow_dispatch:

jobs:
  packer:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/github-actions-packer
          aws-region: us-east-1

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3

      - name: Packer init
        working-directory: infra/packer/ops
        run: packer init .

      - name: Packer validate
        working-directory: infra/packer/ops
        run: packer validate .

      - name: Build AMI
        working-directory: infra/packer/ops
        run: packer build .
